# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review

# - id: doi:10.1016/j.csbj.2020.05.017
#   image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

# - id: doi:10.7554/eLife.32822
#   image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

# ======== Mood Ring ========

# Framework for Ranking Machine Learning Predictions of Limited, Multimodal, and Longitudinal Behavioral Passive Sensing Data: Combining User-Agnostic and Personalized Modeling
- id: doi:10.2196/47805
  image: images/Projects/Moodring/Framework-for-Ranking.png
  tags:
    - Mood Ring

# Predicting depression in adolescents using mobile and wearable sensors: multimodal machine learning-based exploratory study
- id: doi:10.2196/35807
  image: images/Projects/Moodring/Predicting-Depression.png
  tags:
    - Mood Ring

# An Automated Machine Learning Pipeline for Monitoring and Forecasting Mobile Health Data
- id: doi:10.1109/SIEDS52267.2021.9483755
  image: images/Projects/Moodring/SIEDS-2021.png
  tags:
    - Mood Ring


# ======== Melodies ========

# Chords
- id doi:10.1145/3675094.3678495
  image: images/Projects/Melodies/Chords.png
  tags:
    - Melodies

# Sounds of Health: Using Personalized Sonification Models to Communicate Health Information
- id: doi:10.1145/3570346
  image: images/Projects/Melodies/Sounds-Of-Health-Cover.jpg
  tags:
    - Melodies

# Changing Your Tune: Lessons for Using Music to Encourage Physical Activity
- id: doi:10.1145/3659611
  image: images/Projects/Melodies/Changing-Your-Tune-Cover.jpg
  tags:
    - Melodies


# ======== Rhythms ========

# Identifying Links Between Productivity and Biobehavioral Rhythms Modeled From Multimodal Sensor Streams: Exploratory Quantitative Study
- id: doi:10.2196/47194 
  image: images/Projects/Rhythms/Identifying_Links.png
  tags:
    - Rhythms

# Modeling Regularity and Predictability in Human Behavior from Multidimensional Sensing Signals and Personal Characteristics
- id: doi:10.1109/ICMLA58977.2023.00045
  image: images/Projects/Rhythms/Modeling_Regularity.jpg
  tags:
    - Rhythms

# Personalization in Circadian Rhythm-Based Event Scheduling
- id: doi:10.1109/SIEDS58326.2023.10137806
  image: images/Projects/Rhythms/2023-SIEDS-Cover.jpg
  tags:
    - Rhythms

# A Computational Framework for Modeling Biobehavioral Rhythms from Mobile and Wearable Data Streams
- id: doi:10.1145/3510029
  image: images/Projects/Rhythms/A_Computational_Framework.png
  tags:
    - Rhythms

# Daily Trajectory Prediction Using Temporal Frequent Pattern Tree
- id: doi:10.1007/978-981-16-2380-6_29
  image: images/Projects/Rhythms/Daily_Trajectory.png
  tags:
    - Rhythms

# Towards a Computational Framework for Automated Discovery and Modeling of Biological Rhythms from Wearable Data Streams
- id: doi:10.1007/978-3-030-82199-9_44
  image: images/Projects/Rhythms/Towards_Computational_Framework.png
  tags:
    - Rhythms

# Modeling Biological Rhythms to Predict Mental and Physical Readiness
- id: doi:10.1109/SIEDS49339.2020.9106683
  image: images/Projects/Rhythms/2020-SIEDS-Cover.png
  tags:
    - Rhythms

# CoRhythMo: A Computational Framework for Modeling Biobehavioral Rhythms from Mobile and Wearable Data Streams
- id: doi:10.1101/2020.08.10.244020
  image: images/Projects/Rhythms/CoRhythMo.png
  tags:
    - Rhythms

# Identifying Behavioral Phenotypes of Loneliness and Social Isolation with Passive Sensing: Statistical Analysis, Data Mining and Machine Learning of Smartphone and Fitbit Data
- id: doi:10.2196/13209
  image: images/Papers/behavioral-phenotypes.png
  tags:
    - Rhythms

# Modeling Biobehavioral Rhythms with Passive Sensing in the Wild: A Case Study to Predict Readmission Risk after Pancreatic Surgery
- id: doi:10.1145/3314395
  image: images/Projects/Rhythms/Modeling_Biobehavioral_Rhythms-IMWUT2019.jpg
  tags:
    - Rhythms

# ======== Nutrition ========
# Towards an Accessible, Noninvasive Micronutrient Status Assessment Method: A Comprehensive Review of Existing Techniques
- id: arXiv:2408.11877
  image: images/Projects/Nutrition/nutrition-graphic.png
  type: preprint
  tags:
    - Nutrition

# ======== Injustice ========

# Why Algorithms Remain Unjust: Power Structures Surrounding Algorithmic Activity
- id: arXiv:2405.18461
  image: images/Papers/injustice.png
  type: preprint

# ======= Adaptive Humanoid Robots =======

# A Self Learning System for Emotion Awareness and Adaptation in Humanoid Robots
- id: 10.1109/RO-MAN53752.2022.9900581
  image: images/Projects/Adaptive_Robots/self_learning.jpg
  tags:
    - Adaptive Humanoid Robots

# Adaptive Humanoid Robots for Pain Management
- id: doi:10.1145/3434074.3447224
  image: images/Projects/Adaptive_Robots/pain.jpg
  tags:
    - Adaptive Humanoid Robots
